export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_COUNTRIES_ERROR = 'GET_COUNTRIES_ERROR';
export const GET_COUNTRIES_BEGIN = 'GET_COUNTRIES_BEGIN';
export const GET_COUNTRIES_REGION = 'GET_COUNTRIES_REGION';